# Generated by Django 2.2.2 on 2019-06-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0016_auto_20180707_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='t_image',
        ),
    ]
